### ISSUE TITLE
TypeF中bate，alpha0和alpha2的

### ISSUE THREAD

**Issue by hicfd** [yaoyuanyylyy/abestudy#1]
TypeF中bate，alpha0和alpha2与官方SM9中的参数定义并不一样，而您实现了这个算法并且非常完善。我有点不明白如何从SM9中的参数获取JPBC中TypeF的bate，alpha0和alpha2参数

**Comment by yaoyuanyylyy** [comment]
看下这个类 SM9CurveGenerator.java
